Traceback (most recent call last):
  File "c:\Users\fedot\Desktop\pdz\test\main_test.py", line 111, in <module>
    try: main ()
  File "c:\Users\fedot\Desktop\pdz\test\main_test.py", line 107, in main
    sync_repo (repo, "")
  File "c:\Users\fedot\Desktop\pdz\test\main_test.py", line 87, in sync_repo
    master_ref = repo.get_git_refs      ('heads/master')[0]
TypeError: get_git_refs() takes 1 positional argument but 2 were given
